apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-instance
  namespace: awx
spec:
  replicas: 1
  # Disable ingress controller usage
  ingress_type: none

  # Configure NodePort for external access
  service_type: NodePort

  # You can optionally set NodePort manually (optional)
  nodeport_port: 30080
  #nodeport_tls_port: 30443

  # Basic resource settings
  web_replicas: 1
  task_replicas: 1
  
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname  # Example key
                operator: In
                values:
                  - rke-node1  # List node names that should receive the pods
                  #- node-2
  # pg_capacity: 10Gi
  # postgres_database:: awx
  # # pv and pvc assigment:
  # volumes:
  #   - name: awx-postgres-volumes
  #     persistentVolumeClaim:
  #       claimName: awx-postgres-pvc