apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-instance
  namespace: awx
spec:
  replicas: 2

  # Disable ingress controller usage
  ingress_type: none

  # Configure NodePort for external access
  service_type: NodePort

  # You can optionally set NodePort manually (optional)
  nodeport_port: 30080
  #nodeport_tls_port: 30443

  # Basic resource settings
  web_replicas: 1
  task_replicas: 1
 
  # pg_capacity: 10Gi
  # postgres_database:: awx
  # # pv and pvc assigment:
  # volumes:
  #   - name: awx-postgres-volumes
  #     persistentVolumeClaim:
  #       claimName: awx-postgres-pvc