---
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: awx-operator
spec:
  clusterScope: true

  defaultNamespace: awx-operator
  targetNamespace: awx-operator
  resources:
    - manifests/
  helm:
    takeOwnership: true
    releaseName: awx-operator
    repo: https://ansible-community.github.io/awx-operator/
    chart: awx-operator
    version: 3.2.0
    installCrds: true
    targetCustomizations:
    #- name: local
      - clusterSelector:
          matchLabels:
            environment: rke2
    #valuessFiles:
    #  - values.yaml
    